# Generated by Django 3.2.6 on 2021-08-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=400)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
